# Generated by Django 3.1.7 on 2021-07-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_photo_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
