# Generated by Django 3.1.7 on 2021-06-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
