# Generated by Django 3.1.7 on 2021-06-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_program_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='insight',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
