# Generated by Django 3.1.7 on 2021-06-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_program_insight'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='day_five',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='day_four',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='day_one',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='day_seven',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='day_six',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='day_three',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='program',
            name='insight',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='program',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='program',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
