# Generated by Django 3.1.7 on 2021-07-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_auto_20210603_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='day_two',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
